#!/usr/bin/env python3
"""Build grammar/atml.abnf from the pinned TOML baseline plus atml-ext.abnf.

Enforces the additivity invariant: the extension file may only
  a) extend existing baseline rules via "=/", or
  b) define new rules whose names start with "atml-".
By construction, every valid TOML 1.1.0 document is a valid ATML document.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASELINE = ROOT / "grammar" / "toml-1.1.0.abnf"
EXTENSION = ROOT / "grammar" / "atml-ext.abnf"
OUTPUT = ROOT / "grammar" / "atml.abnf"

HEADER = """\
;; =====================================================================
;; ATML -- Advanced TOML ("Atom-L")
;; A human-friendly, DRY-centric configuration language extending TOML.
;;
;; This grammar is the concatenation of two parts (built by
;; tools/build_atml.py -- do not edit this file directly):
;;   1. The official, unmodified TOML v1.1.0 ABNF (vendored, pinned),
;;      by Tom Preston-Werner, Pradyun Gedam, et al. (MIT License).
;;      Source: https://github.com/toml-lang/toml/blob/1.1.0/toml.abnf
;;   2. Purely additive ATML extension rules: only "=/" incremental
;;      alternatives and new "atml-*" rules. By construction, every
;;      valid TOML 1.1.0 document is a valid ATML document.
;;
;; Normative disambiguation rule (spec text, not expressible in ABNF):
;;   If a value parses as a standard TOML value, it IS a standard TOML
;;   value. TOML interpretations always take precedence over ATML ones.
;;
;; ATML is a grateful extension of TOML, not a replacement.
;; =====================================================================

"""

RULE_DEF = re.compile(r"^([A-Za-z][A-Za-z0-9-]*)\s*(=/|=)", re.M)


def main() -> int:
    base = BASELINE.read_text(encoding="ascii")
    ext = EXTENSION.read_text(encoding="ascii")

    base_rules = {m.group(1).lower() for m in RULE_DEF.finditer(base)}
    violations = []
    for m in RULE_DEF.finditer(ext):
        name, op = m.group(1).lower(), m.group(2)
        if op == "=" and not name.startswith("atml-"):
            violations.append(f"  rule '{name}' redefines '=' but is not an atml-* rule")
        if op == "=/" and name not in base_rules and not name.startswith("atml-"):
            violations.append(f"  rule '{name}' extends an unknown baseline rule via '=/'")

    if violations:
        print("ADDITIVITY VIOLATION:\n" + "\n".join(violations))
        return 1

    OUTPUT.write_text(HEADER + base + "\n" + ext, encoding="ascii", newline="\n")
    print(f"OK: built {OUTPUT.relative_to(ROOT)} "
          f"({len(base_rules)} baseline rules, purely additive extension).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
